version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: ledger-postgres
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d ledger"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: ledger-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - INSIDE://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "19092:19092"  # external Kafka
      - "9644:9644"    # admin HTTP
    healthcheck:
      test: ["CMD-SHELL", "curl -s localhost:9644/v1/status/ready | grep -q ready"]
      interval: 5s
      timeout: 5s
      retries: 60

volumes:
  pgdata:
