spring:
  application:
    name: event-ledger
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: ledger
    password: ledger
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:19092

server:
  port: 8080
